/**
 * One-click newsletter unsubscribe.
 *
 * Links are generated by /api/contact with an HMAC token so only the
 * recipient of the confirmation email can unsubscribe that address.
 * Marks the contact `unsubscribed` in the Resend Audience and renders a
 * small confirmation page. Also accepts POST for RFC 8058 one-click
 * unsubscribe (the List-Unsubscribe-Post header in our emails).
 */

const crypto = require("crypto");

const RESEND_AUDIENCES = "https://api.resend.com/audiences";
const AUDIENCE_ID = process.env.RESEND_AUDIENCE_ID || "6f12a47e-8aad-4e30-a28a-6dfab62ccabf";

function unsubToken(email, key) {
  return crypto.createHmac("sha256", key).update(email.toLowerCase()).digest("hex").slice(0, 32);
}

function esc(s) {
  return String(s).replace(/[&<>"']/g, function (c) {
    return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c];
  });
}

function page(title, body) {
  return `<!DOCTYPE html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="robots" content="noindex"><title>${title} — Daniel Faiella Insurance</title></head>
<body style="margin:0;font-family:'Public Sans',-apple-system,BlinkMacSystemFont,sans-serif;background:#14213d;color:#1a2236;display:flex;align-items:center;justify-content:center;min-height:100vh;padding:24px;box-sizing:border-box">
<div style="background:#fbfaf6;border-radius:18px;max-width:460px;padding:38px 34px;text-align:center">
<div style="width:52px;height:52px;border-radius:50%;background:#b48a3c;color:#14213d;display:inline-flex;align-items:center;justify-content:center;font-size:26px;font-weight:700;font-family:Georgia,serif">DF</div>
<h1 style="font-family:Georgia,'Times New Roman',serif;font-size:26px;margin:18px 0 10px;color:#14213d">${title}</h1>
${body}
<p style="font-size:13px;color:#5b6478;margin:26px 0 0"><a href="https://faiellainsurance.com" style="color:#8c6b27;font-weight:600;text-decoration:none">← Back to faiellainsurance.com</a></p>
</div></body></html>`;
}

const helpLine = `<p style="font-size:15px;line-height:1.6;color:#5b6478;margin:0">Need a hand? Email <a href="mailto:hello@faiellainsurance.com" style="color:#8c6b27;font-weight:600">hello@faiellainsurance.com</a> or call/text 775-315-5572.</p>`;

module.exports = async function handler(req, res) {
  const html = (status, markup) => {
    res.statusCode = status;
    res.setHeader("Content-Type", "text/html; charset=utf-8");
    return res.end(markup);
  };

  const apiKey = process.env.RESEND_API_KEY;
  const q = req.query || {};
  const email = String(q.e || "").trim();
  const token = String(q.t || "").trim();

  if (!apiKey) {
    console.error("RESEND_API_KEY is not set");
    return html(500, page("Something went wrong", helpLine));
  }

  const expected = unsubToken(email, apiKey);
  const valid =
    email &&
    token.length === expected.length &&
    crypto.timingSafeEqual(Buffer.from(token), Buffer.from(expected));

  if (!valid) {
    return html(400, page(
      "That link didn't work",
      `<p style="font-size:15px;line-height:1.6;color:#1a2236;margin:0 0 14px">This unsubscribe link looks incomplete or expired.</p>` +
        `<p style="font-size:15px;line-height:1.6;color:#1a2236;margin:0 0 14px">Email <a href="mailto:hello@faiellainsurance.com" style="color:#8c6b27;font-weight:600">hello@faiellainsurance.com</a> and we'll remove you right away.</p>`
    ));
  }

  try {
    const r = await fetch(`${RESEND_AUDIENCES}/${AUDIENCE_ID}/contacts/${encodeURIComponent(email)}`, {
      method: "PATCH",
      headers: { Authorization: `Bearer ${apiKey}`, "Content-Type": "application/json" },
      body: JSON.stringify({ unsubscribed: true }),
    });
    if (!r.ok) {
      console.error("Unsubscribe PATCH failed:", r.status, await r.text().catch(() => ""));
      return html(502, page(
        "We couldn't process that automatically",
        `<p style="font-size:15px;line-height:1.6;color:#1a2236;margin:0 0 14px">Sorry — something went wrong on our end.</p>` + helpLine
      ));
    }
  } catch (e) {
    console.error("Unsubscribe crashed:", e);
    return html(502, page(
      "We couldn't process that automatically",
      `<p style="font-size:15px;line-height:1.6;color:#1a2236;margin:0 0 14px">Sorry — something went wrong on our end.</p>` + helpLine
    ));
  }

  return html(200, page(
    "You've been unsubscribed",
    `<p style="font-size:15px;line-height:1.6;color:#1a2236;margin:0 0 14px"><strong>${esc(email)}</strong> won't receive the monthly newsletter anymore.</p>` +
      `<p style="font-size:15px;line-height:1.6;color:#1a2236;margin:0 0 14px">Change your mind? Just subscribe again on the homepage anytime.</p>` + helpLine
  ));
};
